//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapBox.Demo.PinBall.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sounds {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sounds() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoapBox.Demo.PinBall.Resources.Sounds", typeof(Sounds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.IO.UnmanagedMemoryStream beat1 {
            get {
                return ResourceManager.GetStream("beat1", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream beat2 {
            get {
                return ResourceManager.GetStream("beat2", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream bonus_fast {
            get {
                return ResourceManager.GetStream("bonus_fast", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream brooomm {
            get {
                return ResourceManager.GetStream("brooomm", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream doodoodoodoo {
            get {
                return ResourceManager.GetStream("doodoodoodoo", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream driiinng2 {
            get {
                return ResourceManager.GetStream("driiinng2", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream flip {
            get {
                return ResourceManager.GetStream("flip", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream rattata_single {
            get {
                return ResourceManager.GetStream("rattata_single", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream tack {
            get {
                return ResourceManager.GetStream("tack", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream tick {
            get {
                return ResourceManager.GetStream("tick", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream time {
            get {
                return ResourceManager.GetStream("time", resourceCulture);
            }
        }
    }
}
