//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapBox.Demo.PinBall.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoapBox.Demo.PinBall.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        public static string Arena_PinBallTable_GameOver {
            get {
                return ResourceManager.GetString("Arena_PinBallTable_GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is over.  Click Ok to Play Again..
        /// </summary>
        public static string Arena_PinBallTable_GameOverMessage {
            get {
                return ResourceManager.GetString("Arena_PinBallTable_GameOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinBall Table.
        /// </summary>
        public static string Arena_PinBallTable_Title {
            get {
                return ResourceManager.GetString("Arena_PinBallTable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Options_PinBallOptions_General {
            get {
                return ResourceManager.GetString("Options_PinBallOptions_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Options_PinBallOptions_General_Sound {
            get {
                return ResourceManager.GetString("Options_PinBallOptions_General_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Ball.
        /// </summary>
        public static string Options_PinBallOptions_Header {
            get {
                return ResourceManager.GetString("Options_PinBallOptions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the spacebar to pull the plunger back and release a ball.  Use the left and right control keys to operate the left and right flipper, respectively..
        /// </summary>
        public static string Pads_Instructions_Text {
            get {
                return ResourceManager.GetString("Pads_Instructions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Pads_Instructions_Title {
            get {
                return ResourceManager.GetString("Pads_Instructions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Ball Demo.
        /// </summary>
        public static string Workbench_AboutBox_ApplicationName {
            get {
                return ResourceManager.GetString("Workbench_AboutBox_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2009 SoapBox Automation Inc., All Rights Reserved..
        /// </summary>
        public static string Workbench_AboutBox_Copyright {
            get {
                return ResourceManager.GetString("Workbench_AboutBox_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under the LGPLv3 License..
        /// </summary>
        public static string Workbench_AboutBox_License {
            get {
                return ResourceManager.GetString("Workbench_AboutBox_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Ok    .
        /// </summary>
        public static string Workbench_AboutBox_Ok {
            get {
                return ResourceManager.GetString("Workbench_AboutBox_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SoapBox Core PinBall Demo.
        /// </summary>
        public static string Workbench_AboutBox_Title {
            get {
                return ResourceManager.GetString("Workbench_AboutBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string Workbench_MainMenu_Help_About {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Instructions.
        /// </summary>
        public static string Workbench_MainMenu_Help_Instructions {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_Help_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Pin Ball Table.
        /// </summary>
        public static string Workbench_MainMenu_View_PinBallTable {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_View_PinBallTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balls: .
        /// </summary>
        public static string Workbench_StatusBar_BallCounter_Balls {
            get {
                return ResourceManager.GetString("Workbench_StatusBar_BallCounter_Balls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: .
        /// </summary>
        public static string Workbench_StatusBar_ScoreDisplay_Score {
            get {
                return ResourceManager.GetString("Workbench_StatusBar_ScoreDisplay_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoapBox Core Pin Ball Demo.
        /// </summary>
        public static string Workbench_Title {
            get {
                return ResourceManager.GetString("Workbench_Title", resourceCulture);
            }
        }
    }
}
